[package]
name = "entanglement"
version = "0.1.0"
authors = ["Gregory Langlais <general@gregorylanglais.com>"]
edition = "2018"
description = "Replication over a network using Rust"
license = "MIT"


[dependencies]
